from item_models import ItemType
from actions import AIActions


INTENTION_MAP = {
    "receber dinheiro": AIActions.PEGAR_DINHEIRO,
    "pegar dinheiro": AIActions.PEGAR_DINHEIRO,
    "dar dinheiro": AIActions.DAR_DINHEIRO,
    "dar item": AIActions.DAR_ITEM,
    "pegar item": AIActions.PEGAR_ITEM,
    "atacar": AIActions.ATACAR,
    "voltar à rotina": AIActions.ROTINA,
    "voltar a rotina": AIActions.ROTINA,
    "idle": AIActions.NENHUMA,
    "nenhuma ação": AIActions.NENHUMA,
    "": AIActions.NENHUMA
}

ITEM_MAP = {
    "arco": ItemType.ARCO,
    "espada": ItemType.ESPADA,
    "bardiche": ItemType.BARDICHE,
    "alabarda": ItemType.ALABARDA,
    "lanca": ItemType.LANCA,
    "machado": ItemType.MACHADO,
    "adaga": ItemType.ADAGA,
    "marreta": ItemType.MARRETA,
    "picareta": ItemType.PICARETA,
    "faca": ItemType.FACA,
    "besta": ItemType.BESTA,
    "katana": ItemType.KATANA,
    "kryss": ItemType.KRYSS,
    "foice": ItemType.FOICE,
    "porrete": ItemType.PORRETE,
    "bordao": ItemType.BORDAO,
    "escudo": ItemType.ESCUDO,
    "broquel": ItemType.BROQUEL,
    "madeira": ItemType.MADEIRA,
    "serra": ItemType.SERRA,
    "tambor": ItemType.TAMBOR,
    "tamborim": ItemType.TAMBORIM,
    "harpa": ItemType.HARPA,
    "alaude": ItemType.ALAUDE,
    "sacola": ItemType.SACOLA,
    "bolsa": ItemType.BOLSA,
    "mochila": ItemType.MOCHILA,
    "couro": ItemType.COURO,
    "pao": ItemType.PAO,
    "bolo": ItemType.BOLO,
    "cookies": ItemType.COOKIES,
    "pizza": ItemType.PIZZA,
    "bandage": ItemType.BANDAGE,
    "bandages": ItemType.BANDAGE,
    "seta": ItemType.SETA,
    "setas": ItemType.SETA,
    "flecha": ItemType.FLECHA,
    "flechas": ItemType.FLECHAS,
    "tesoura": ItemType.TESOURA,
}