services:
  - type: web
    name: notalone-api
    runtime: python
    repo: https://github.com/gnai-creator/ModernUO-NotAlone-AI-API
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ia_service_instruct:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: PORT
        value: 10000
